p                  = {}        -- protect the palouse
p.ape              = s{1}      -- ape
p.root             = s{60}     -- root
p.tempo            = s{120}    -- tempo
p.reverb           = s{1}      -- off 1, on 2
p.rev_return_level = s{0.0}    -- db
p.rev_pre_delay    = s{60.0}   -- ms
p.rev_lf_fc        = s{200.0}  -- hz
p.rev_low_time     = s{6.0}    -- seconds
p.rev_mid_time     = s{6.0}    -- seconds
p.rev_hf_damping   = s{6000.0} -- hz
p.delay_beats      = s{3/4}    -- beats
p.delay_decay      = s{5}      -- seconds
p.delay_lag        = s{0.05}   -- seconds